### ISSUE TITLE
Poposal: Enhance Connect button with  selection of connections

### ISSUE THREAD

**Issue by myonara** [mystiker/webmud3#40]
use the following optional button if there are more then one connecton to handle

* https://primeng.org/splitbutton

for seifenblase there is only one, but a "Verbinden (Seifenblase) could be more explicit.

For UNItopia here are:

* UNItopia
* Orbit
* Uni1993

also the logon to the chracter dashboard should be accessable from that menu.

**Comment by mystiker** [comment]
As we discussed, a package (frontend + backend) will provide the ability to connect to any MUD. To do this, however, the connection must be set in the backend via an environment variable, which is a sufficiently flexible mechanism.

I don't think it makes sense to transfer this responsibility to the front end, since we are building a dedicated client for a MUD and not a universal client. It's not worth the effort right now.

If there are no objections, I will close this issue after a few days.
